### ISSUE TITLE
Could not resolve a require path (JSON)

### ISSUE THREAD

**Issue by Mottie** [rollup/rollup-plugin-node-resolve#114]
I'm seeing the following error:

```
$ rollup -c

index.js → bundle.js...
[!] Error: Could not resolve './data/all' from node_modules\known-css-properties\index.js
Error: Could not resolve './data/all' from node_modules\known-css-properties\index.js
    at error (C:\Users\Me\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:181:12)
    at C:\Users\Me\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:10121:7
    at <anonymous>
```

The node module has an `index.js` that loads in a JSON file from a folder:

```js
module.exports.all = require('./data/all').properties;
```

If I modify the above code to export the JSON data directly, it works as expected.

```js
module.exports.all = [ /* ... */ ];
```

Here are the rollup config and package json files:

### `rollup.config.js`

```js
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
  entry: 'index.js',
  dest: 'bundle.js',
  moduleName: 'test',
  format: 'iife',
  plugins: [
    resolve({
      jsnext: true,
      main: true,
      browser: true,
      preferBuiltins: false
    }),
    commonjs()
  ]
};
```

### `package.json`

```js
{
  "name": "rollup-test",
  "version": "0.1.0",
  "description": "Rollup test of requiring a node_module json file",
  "main": "bundle.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "rollup -c"
  },
  "dependencies": {
    "known-css-properties": "^0.3.0"
  },
  "devDependencies": {
    "rollup-plugin-commonjs": "^8.1.0",
    "rollup-plugin-node-resolve": "^3.0.0"
  }
}
```

**Comment by bfred-it** [comment]
You will need an additional plugin to handle JSON. This one only takes care of path resolution. 

The plugin is https://github.com/rollup/rollup-plugin-json

**Comment by Mottie** [comment]
Hmm, I included the JSON plugin and I'm still seeing the same error.

```js
import resolve from 'rollup-plugin-node-resolve'; // v3.0.0
import commonjs from 'rollup-plugin-commonjs'; // v8.2.1
import json from 'rollup-plugin-json'; // v2.3.0

export default {
  entry: 'index.js',
  dest: 'stylelint-bundle.js',
  moduleName: 'stylelint',
  format: 'iife',
  plugins: [
    json({
      preferConst: true,
      include: 'node_modules/**'
    }),
    resolve({
      jsnext: true,
      main: true,
      browser: true,
      preferBuiltins: false
    }),
    commonjs()
  ]
};
```

Does the plugin order matter?

**Comment by felixrabe** [comment]
Doesn't seem to matter according to https://github.com/rollup/rollup-plugin-json/blob/585fe3d167d22a7152f165f1dbe3d87197c6043b/src/index.js#L10.

Is there a way to `import "../package"` without the explicit `.json` extension?

**Comment by felixrabe** [comment]
Answering myself (Rollup newb here) - This seems to do the trick:

```js
import json from 'rollup-plugin-json'
import resolve from 'rollup-plugin-node-resolve'

export default {
  input: './src/index.js',
  output: {
    file: './lib/index.js',
    format: 'umd',
  },
  plugins: [
    json(),
    resolve({
      extensions: ['.js', '.json'],
    }),
  ],
}
```
