### ISSUE TITLE
Error: Command `rollup -c rollup.config.umd.js && rollup -c rollup.config.esm.js && tsc && ngc` exited with code 1

### ISSUE THREAD

**Issue by hemanthbs12** [rollup/rollup-plugin-node-resolve#148]
when I run `npm run build`, getting this error.

`Error: Command `rollup -c rollup.config.umd.js && rollup -c rollup.config.esm.js && tsc && ngc` exited with code 1
    at ChildProcess.handleSubShellExit (D:\GIT\NPM\FeaturedContent\node_modules\gulp-run\command.js:166:13)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
$ rollup -c rollup.config.umd.js && rollup -c rollup.config.esm.js && tsc && ngc`

**Comment by mecurc** [comment]
I think it can be closed because rollup works perfectly :) Error not here I think.

Also, 0 updates since Mar 2018

**Comment by TrySound** [comment]
@mecurc Thanks man!
