### ISSUE TITLE
[!] TypeError: this.error is not a function

### ISSUE THREAD

**Issue by Yonom** [rollup/rollup-plugin-node-resolve#231]
- Node-Resolve Plugin Version: 5.1.0
- Rollup Version: 1.16.2
- Operating System (or Browser): Windows 10
- Node Version: v10.15.2

### How Do We Reproduce?

Use this config with `rollup -c`.
```
import resolve from 'rollup-plugin-node-resolve';
export default {
    input: 'src/index.js',
    output: {
        file: 'bundle.js',
        format: 'cjs'
    },
    plugins: [resolve()]
}
```

Repository:
https://github.com/Yonom/rollup-test

### Expected Behavior

Rollup builds index.js

### Actual Behavior

> TypeError: this.error is not a function
>     at Object.options (\rollup-test\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:256:14)
>     at applyOptionHook (\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:18404:31)
>     at Array.reduce (<anonymous>)
>     at getInputOptions$1 (\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:18422:41)
>     at Object.rollup (\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:18466:30)
>     at build (\AppData\Roaming\npm\node_modules\rollup\bin\rollup:1050:19)
>     at \AppData\Roaming\npm\node_modules\rollup\bin\rollup:1840:24
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
>     at startup (internal/bootstrap/node.js:283:19)

**Comment by lukastaegert** [comment]
You are using an outdated Rollup version. Fix for the broken error message at #232
