### ISSUE TITLE
Error: Could not load [object Object]

### ISSUE THREAD

**Issue by Dan503** [rollup/rollup-plugin-node-resolve#242]
- Node-Resolve Plugin Version: 5.2.0
- Rollup Version: 1.27.2
- Operating System (or Browser): Windows 10
- Node Version: 12.13.0

### How Do We Reproduce?

Reproduction steps are outlined in this reduced test case repo:

https://github.com/Dan503/BUG-rollup-plugin-node-resolve/tree/master

Note this part of gulpfile.js in particular:

```js
const rollupJS = (inputFile, options) => {
	return () => {
		return (
			rollup({
				input: options.basePath + inputFile,
				format: options.format,
				sourcemap: options.sourcemap,
				plugins: [resolve()], // <<-- This is the line that calls rollup-plugin-node-resolve
			})
				.pipe(source(inputFile, options.basePath))
				.pipe(buffer())
				.pipe(sourcemaps.init({ loadMaps: true }))
				.pipe(sourcemaps.write('.'))
				.pipe(gulp.dest(options.distPath))
		)
	}
}
```

### Expected Behavior

It should not error

### Actual Behavior

It throws this error when trying to run the code:

```js
Error: Could not load [object Object]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at C:\xxx\Bug-recreations\rollup-plugin-node-resolve\node_modules\rollup-stream\node_modules\rollup\dist\rollup.js:9715:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Comment by Dan503** [comment]
@shellscape this issue is still relevant. Please transfer it to the new repo.
