### ISSUE TITLE
Could not resolve 'vue'

### ISSUE THREAD

**Issue by pbelyaev** [rollup/rollup-plugin-node-resolve#54]
rollup.config.js

```javascript
import nodeResolve from 'rollup-plugin-node-resolve'

export default {
    entry: 'src/bootstrap.js',

    plugins: [
        nodeResolve()
    ],

    dest: 'dist/app.js'
}
```

What I've got:
```
Could not resolve 'vue' from /Users/belyaev/www/vuex-tutorial/src/bootstrap.js
Error: Could not resolve 'vue' from /Users/belyaev/www/vuex-tutorial/src/bootstrap.js
    at Error (native)
    at /Users/belyaev/www/vuex-tutorial/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Users/belyaev/www/vuex-tutorial/node_modules/resolve/lib/async.js:46:14
    at process (/Users/belyaev/www/vuex-tutorial/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/belyaev/www/vuex-tutorial/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/belyaev/www/vuex-tutorial/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/belyaev/www/vuex-tutorial/node_modules/resolve/lib/async.js:92:31)
    at /Users/belyaev/www/vuex-tutorial/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

**Comment by TrySound** [comment]
Do you have vue in your dependenvies?

**Comment by TrySound** [comment]
Weird. I can't reproduce. I got this because vue package is commonjs.
```js
Module D:\_host\sandbox\rollup-sandbox\v\node_modules\vue\dist\vue.common.js does not export default (imported by D:\_ho
st\sandbox\rollup-sandbox\v\src\bootstrap.js)
```

**Comment by pbelyaev** [comment]
Should be something wrong with my build. Made new one and it's working. Sorry for that.
